CREATE TABLE IF NOT EXISTS links (
	id        TEXT   PRIMARY KEY,
	short     TEXT   NOT NULL DEFAULT '',
	long      TEXT   NOT NULL DEFAULT '',
	created   BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
	last_edit BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
	owner     TEXT   NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS stats (
	id      TEXT    NOT NULL DEFAULT '',
	created BIGINT  NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
	clicks  INTEGER
);
